# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/roeyazroel/kubectl-pfw/discussions
    about: Please ask and answer questions here.
